### PR TITLE
Fix spelling mistake in New-AzureADServicePrincipal.md

### PR DESCRIPTION
**Pull request by cdahlin**
atlernative -> alternative

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[50a60f1](https://github.com/cdahlin/azure-docs-powershell-azuread/commits/50a60f13b7f3dac4635835541ece30a9a23063d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADServicePrincipal.md](https://github.com/cdahlin/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/New-AzureADServicePrincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadserviceprincipal?view=azureadps-2.0&branch=pr-en-us-737) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202111151807237690-737%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T18%3A08%3A38Z&sr=b&sp=r&sig=vvWd2E9iqp7bEnzuq41js57%2B2Xoj5PWptkUD1P2Vnl8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hi @cdahlin, thanks for your contribution. Please redo this PR and use master as the base branch instead of live. Thanks.

**Comment by cdahlin** [comment]
> Hi @cdahlin, thanks for your contribution. Please redo this PR and use master as the base branch instead of live. Thanks.

@msewaweru OK, changed it to master branch. Hope everything is correct now.

**Comment by msewaweru** [comment]
@CelesteDG , this is good to go.

**Pull request merged**
