### PR TITLE
Update Set-MsolPasswordPolicy.md

### PR DESCRIPTION
**Pull request by pfsantosaad**
-Domainname switch is required, we are not able to make the call without targeting a specific domain.
Removing exemple 1 adn also references to the tenant to not create confusion

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[c55a729](https://github.com/pfsantosaad/azure-docs-powershell-azuread/commits/c55a72921d7711053acfc17e6b99a925c26c76c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Set-MsolPasswordPolicy.md](https://github.com/pfsantosaad/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Set-MsolPasswordPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/set-msolpasswordpolicy?view=azureadps-1.0&branch=pr-en-us-691) (azureadps-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C25%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202108251101075815-691%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=1ldGAxhT9zmr8I4DJRPm9v%2BKZUiGrgBPiT2KCUHj7sY%3D&st=2021-08-25T10%3A57%3A07Z&se=2021-09-25T11%3A02%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hello @pfsantosaad, thanks for your contribution. I will review your PR and would request that you create it against the master branch. PRs done against the live branch cannot be merged.

**Comment by msewaweru** [comment]
@pfsantosaad, sorry if my earlier comment was not clear. Please redo this PR and have the base branch set to 'master' instead of 'live' per our policy. Thank you.

**Comment by msewaweru** [comment]
Closing this. Refer to [PR #702](https://github.com/Azure/azure-docs-powershell-azuread/pull/702)

**Pull request closed without merging**
