### PR TITLE
Update New-AzureADMSGroup.md

### PR DESCRIPTION
**Pull request by PeterDeThier-MSFT**
The issue below still appears to be active in version 2.0.2.140 of the AzureAD module:

https://github.com/Azure/azure-docs-powershell-azuread/issues/717

I'm updating the documentation for the parameter to clarify that the AzureADPreview module needs to be used to create dynamic groups, AzureAD does not appear to support it.

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[edd6057](https://github.com/PeterDeThier-MSFT/azure-docs-powershell-azuread/commits/edd6057ead058121ee5020220a8ee7375e26c4d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSGroup.md](https://github.com/PeterDeThier-MSFT/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/New-AzureADMSGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsgroup?view=azureadps-2.0&branch=pr-en-us-819) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C5%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202205051433189551-819%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-05T14%3A34%3A25Z&sr=b&sp=r&sig=6wHHWm62SOYpHppdL3cS1x0pwpT5Ay3urrZyV3I82X8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Thanks @PeterDeThier-MSFT for your contribution. Please redo this PR with main as the base branch instead of live.

**Comment by billmath** [comment]
Docs Build status updates of commit _[edd6057](https://github.com/PeterDeThier-MSFT/azure-docs-powershell-azuread/commits/edd6057ead058121ee5020220a8ee7375e26c4d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Get-MsolDirSyncFeatures.md](https://github.com/PeterDeThier-MSFT/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Get-MsolDirSyncFeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/get-msoldirsyncfeatures?view=azureadps-1.0&branch=pr-en-us-819) (azureadps-1.0) |
[azureadps-2.0/AzureAD/Get-AzureADContact.md](https://github.com/PeterDeThier-MSFT/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADContact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadcontact?view=azureadps-2.0&branch=pr-en-us-819) (azureadps-2.0) |
[azureadps-2.0/AzureAD/New-AzureADMSGroup.md](https://github.com/PeterDeThier-MSFT/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/New-AzureADMSGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsgroup?view=azureadps-2.0&branch=pr-en-us-819) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202205061338244691-819%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T13%3A39%3A33Z&sr=b&sp=r&sig=sC3jGlBdCQE2tJaCHmatfsXM4N7Zsz0MKc1RiGVuklA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by PeterDeThier-MSFT** [comment]
> Thanks @PeterDeThier-MSFT for your contribution. Please redo this PR with main as the base branch instead of live.

Hi, I've closed this PR and opened a new one:

https://github.com/Azure/azure-docs-powershell-azuread/pull/820

**Pull request closed without merging**
