### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by jhayek24**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[f4fd2e6](https://github.com/jhayek24/azure-docs-powershell-azuread/commits/f4fd2e6762ccbc64a0c56a53ecf96373e2dd6600)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md](https://github.com/jhayek24/azure-docs-powershell-azuread/blob/patch-2/docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/using-extension-attributes-sample?view=azureadps-2.0&branch=pr-en-us-797) (azureadps-2.0) | [Details](#user-content-38222f34cf69869508fe7181bebaab47-22a7deb5)

<a id="38222f34cf69869508fe7181bebaab47-22a7deb5"></a>
### [docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md](https://github.com/jhayek24/azure-docs-powershell-azuread/blob/patch-2/docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C28%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202203282313377755-797%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-28T23%3A14%3A51Z&sr=b&sp=r&sig=qWcDvkVkg1lsC0mKJT3TnTKvBnm%2FJg0sHgO1wzus0Mk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Thanks @jhayek24 for your contribution.

@CelesteDG , this is good to go.

**Comment by msewaweru** [comment]
Added the missing description in [PR 801](https://github.com/Azure/azure-docs-powershell-azuread/pull/801). Closing this. Thanks @jhayek24 for your contribution.

**Comment by msewaweru** [comment]
Added the missing description in [PR 801](https://github.com/Azure/azure-docs-powershell-azuread/pull/801). Closing this. Thanks @jhayek24 for your contribution.

**Comment by kimhubgit** [comment]
.

**Pull request closed without merging**
