### PR TITLE
Patch 1 - Get-AzureADGroup vs Get-AzureADMSGroup

### PR DESCRIPTION
**Pull request by tlourey**
Updated doco for Get-AzureADGroup vs Get-AzureADMSGroup with regards to using AzureAD Graph vs MSGraph. This took me a little time to figure out until I see the comments on [https://techcommunity.microsoft.com/t5/azure-active-directory-identity/new-enhancements-to-the-azuread-powershell-2-0-preview-manage/ba-p/245153](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/new-enhancements-to-the-azuread-powershell-2-0-preview-manage/ba-p/245153]) and realised I wasn't the first person to get confused. 

[1st Comment](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/new-enhancements-to-the-azuread-powershell-2-0-preview-manage/bc-p/1065088/highlight/true#M1813)
[2nd Comment](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/new-enhancements-to-the-azuread-powershell-2-0-preview-manage/bc-p/2507340/highlight/true#M3592)

This may need to be done to all AD vs ADMS pages but at least this is start. 

PS: Also, not sure why there are two merged PR's in Patch-1 which is what I folked when I pressed 'Edit' from docs.microsoft.com. I'm guessing there is a patch-1 branch on the actual repo that may need to be deleted.

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[c273b86](https://github.com/tlourey/azure-docs-powershell-azuread/commits/c273b86c8cb5a50e5dd4986a371250831ae0c06d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/toc.yml](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadgroup?view=azureadps-2.0&branch=pr-en-us-752) (azureadps-2.0) | [Details](#user-content-6fc9c3913fdc3f0b785275896ec148b3-a6438099)
[azureadps-1.0/toc.yml](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/add-msoladministrativeunitmember?view=azureadps-1.0&branch=pr-en-us-752) (azureadps-1.0) | [Details](#user-content-1b96581cb0e466f86082bb3a86b4ee98-a6438099)
[azureadps-2.0-preview/toc.yml](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/add-azureadadministrativeunitmember?view=azureadps-2.0-preview&branch=pr-en-us-752) (azureadps-2.0-preview) | [Details](#user-content-b02ffb1e1c40f25a9c0b5d2a8eb585de-a6438099)
[azureadps-2.0/AzureAD/Get-AzureADGroup.md](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadgroup?view=azureadps-2.0&branch=pr-en-us-752) (azureadps-2.0) |
[azureadps-2.0/AzureAD/Get-AzureADMSGroup.md](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADMSGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsgroup?view=azureadps-2.0&branch=pr-en-us-752) (azureadps-2.0) |

<a id="6fc9c3913fdc3f0b785275896ec148b3-a6438099"></a>
### [azureadps-2.0/toc.yml](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/toc.yml)
 - **Line 5, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#administrative-units' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 26, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-application-management' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 45, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-connector-management' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 66, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#applications' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 109, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#azuread' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 210, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#certificate-authorities' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 221, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#connect-to-your-directory' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 228, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contacts' in 'azureadps-2.0/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 247, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contracts' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 252, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#deleted-objects' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 257, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#devices' in 'azureadps-2.0/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 282, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 291, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-objects' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 296, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-roles' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 325, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#domains' in 'azureadps-2.0/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 344, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#extension-properties' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 349, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#groups' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 404, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#oauth2' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 411, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#policies' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 418, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#service-principals' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 465, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#users' in 'azureadps-2.0/AzureAD/index.yml'.`````

<a id="1b96581cb0e466f86082bb3a86b4ee98-a6438099"></a>
### [azureadps-1.0/toc.yml](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/toc.yml)
 - **Line 5, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#msonline' in 'azureadps-1.0/MSOnline/index.yml'.`````

<a id="b02ffb1e1c40f25a9c0b5d2a8eb585de-a6438099"></a>
### [azureadps-2.0-preview/toc.yml](https://github.com/tlourey/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/toc.yml)
 - **Line 5, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#administrative-units' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 50, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 83, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-application-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 102, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-connector-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 123, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#applications' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 174, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#azureadpreview' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 251, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#certificate-authorities' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 262, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#connect-to-your-directory' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 271, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contacts' in 'azureadps-2.0-preview/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 290, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contracts' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 295, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#custom-security-attributes' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 316, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#deleted-objects' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 329, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#devices' in 'azureadps-2.0-preview/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 354, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 363, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-auditing' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 370, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-objects' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 375, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-roles' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 390, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-settings' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 403, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#domains' in 'azureadps-2.0-preview/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 422, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#extension-properties' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 427, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#groups' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 482, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#identity-provider-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 493, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#oauth2' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 500, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#object-settings' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 511, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#policies' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 528, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#privileged-role-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 551, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#role-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 568, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#service-principals' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 623, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#staged-rollout' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 638, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#trust-framework-policy-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 649, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#users' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201060920592569-752%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T09%3A22%3A05Z&sr=b&sp=r&sig=J1KBVpak%2FJqFwxyhB6K3TpDZiCPnJMgLEhHzzLxM4gA%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by tlourey** [comment]
While i'm not sure, I think those warnings are specifc to the merges that are on the public patch-1 branch. Hopefully this doesn't stop these changes being made.

**Comment by msewaweru** [comment]
Thanks @tlourey for your contribution.

@CelesteDG, this is good to go.

**Comment by tlourey** [comment]
@CelesteDG is there any reason the common paramaters are not showing up on the live site or is it just a caching thing?

[Get-AzureADMSGroup](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsgroup?view=azureadps-2.0)

**Comment by msewaweru** [comment]
Thanks @tlourey for your query. I notice this behavior across all cmdlets. Allow me to find out why it is that way.

**Pull request merged**
