### PR TITLE
[Azure AD Preview] Administrative units update

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[ffcec52](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/ffcec528bfe06231f0ec4ea04bef71471b964eab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/New-AzureADMSAdministrativeUnitMember.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/adminunits-preview/azureadps-2.0-preview/AzureAD/New-AzureADMSAdministrativeUnitMember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsadministrativeunitmember?view=azureadps-2.0-preview&branch=pr-en-us-742) (azureadps-2.0-preview) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C25%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202111251234514318-742%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-26T12%3A35%3A45Z&sr=b&sp=r&sig=k76jaF2wTAAwHpd0L4grlduAZ%2FjZbuLWKfqDMZrJZSM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[b6fb4eb](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/b6fb4eb02ccba5f7762fa9e2b19fd32b0fe6bc3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/New-AzureADMSAdministrativeUnit.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/adminunits-preview/azureadps-2.0-preview/AzureAD/New-AzureADMSAdministrativeUnit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsadministrativeunit?view=azureadps-2.0-preview&branch=pr-en-us-742) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSAdministrativeUnitMember.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/adminunits-preview/azureadps-2.0-preview/AzureAD/New-AzureADMSAdministrativeUnitMember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsadministrativeunitmember?view=azureadps-2.0-preview&branch=pr-en-us-742) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSAdministrativeUnit.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/adminunits-preview/azureadps-2.0-preview/AzureAD/Set-AzureADMSAdministrativeUnit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsadministrativeunit?view=azureadps-2.0-preview&branch=pr-en-us-742) (azureadps-2.0-preview) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201240654105889-742%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T06%3A55%3A23Z&sr=b&sp=r&sig=X6xr1ChmHPNqJecu2R%2FQtT8n6ifHdlk2dLcfzTp74VY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by CelesteDG** [comment]
@msewaweru Where are you on this PR? It's still marked draft from end of Nov. Please check if this PR is still valid or needs to get updated. Thanks.

**Comment by msewaweru** [comment]
> @msewaweru Where are you on this PR? It's still marked draft from end of Nov. Please check if this PR is still valid or needs to get updated. Thanks.

Hi @CelesteDG, this PR is awaiting the rollout of the actual cmdlets. We had touched base with the PM and did some updates on the PR towards the end of Jan and he indicated the rollout could happen in about a month. I will check with him towards the end of this month.

**Comment by CelesteDG** [comment]
Appreciate the update. Thank you, @msewaweru

**Comment by msewaweru** [comment]
@CelesteDG, this is ready now. The cmdlets were finally rolled out. Thanks.

**Pull request merged**
