### PR TITLE
Update - JH

### PR DESCRIPTION
**Pull request by jhayek24**
"Retrieve a the value of a specific extension property for a user" -- removed the "a"

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[a7f123b](https://github.com/jhayek24/azure-docs-powershell-azuread/commits/a7f123b6c8a371fe141f7e6ae5abb04854f74df4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md](https://github.com/jhayek24/azure-docs-powershell-azuread/blob/patch-1/docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/using-extension-attributes-sample?view=azureadps-2.0&branch=pr-en-us-796) (azureadps-2.0) | [Details](#user-content-38222f34cf69869508fe7181bebaab47-ad4254c6)

<a id="38222f34cf69869508fe7181bebaab47-ad4254c6"></a>
### [docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md](https://github.com/jhayek24/azure-docs-powershell-azuread/blob/patch-1/docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202203240542005746-796%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T05%3A43%3A28Z&sr=b&sp=r&sig=mIASxFa1BfccEqmM5ZLzAb0UXSy2YHLE9ZOp9qMG0DA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hi @jhayek24 , thanks for your contribution. Please redo this PR with main as the base branch instead of live. Thanks.

**Comment by jhayek24** [comment]
Thank you !

Is it correct now or am I still missing something?

Thanks !

**Comment by msewaweru** [comment]
@jhayek24 how to tell your base branch, at the top it shows as highlighted on the image below. It still shows that your base branch is live instead of main.

image

**Comment by msewaweru** [comment]
@jhayek24 ,sorry just saw the [new PR](https://github.com/Azure/azure-docs-powershell-azuread/pull/797) you created. Proceeding to close this.

**Pull request closed without merging**
