### PR TITLE
Removed examples that use parameters only available in the Preview mo…

### PR DESCRIPTION
**Pull request by msewaweru**
…dule

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[723bcb1](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/723bcb10d49f19b759409d9f85d90c214a74527a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSGroup.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/issue-717/azureadps-2.0/AzureAD/New-AzureADMSGroup.md) | :x:Error | | [Details](#user-content-2a0858d533bed3579d3c972680d2e365-633fb99f)
[azureadps-2.0/AzureAD/index.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/issue-717/azureadps-2.0/AzureAD/index.yml) | :warning:Warning | | [Details](#user-content-37bfae49af1a8a6b2e01cf868c49bb89-633fb99f)

<a id="2a0858d533bed3579d3c972680d2e365-633fb99f"></a>
### [azureadps-2.0/AzureAD/New-AzureADMSGroup.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/issue-717/azureadps-2.0/AzureAD/New-AzureADMSGroup.md)
 - **Line 0, Column 0**: **[Error: MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/ch2n-s/azureadps-2.0/AzureAD/New-AzureADMSGroup.md:14:(107) '

### Example : Create a group assignable to rol...'
 Expect Heading level 2, please try to use PlatyPS validate the content
`````

<a id="37bfae49af1a8a6b2e01cf868c49bb89-633fb99f"></a>
### [azureadps-2.0/AzureAD/index.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/issue-717/azureadps-2.0/AzureAD/index.yml)
 - **Line 218, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADMSAuthorizationPolicy'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C1%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202111011434126603-728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-02T14%3A35%3A12Z&sr=b&sp=r&sig=uSBSvVviMUzgPOZGleX5UDAG3%2BhCZ1xjkfcwKAuW9Nc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[238078b](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/238078bc6e73a7169cef525ad4d9c3b0dac2315d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSGroup.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/issue-717/azureadps-2.0/AzureAD/New-AzureADMSGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsgroup?view=azureadps-2.0&branch=pr-en-us-728) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C1%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202111011437243773-728%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-02T14%3A38%3A27Z&sr=b&sp=r&sig=eaym1sex489fd0xpw86%2F76YfyLjtiqGdh1z7vcw3b74%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Fixes #717

**Comment by msewaweru** [comment]
@CelesteDG , please review this.

**Pull request merged**
