### PR TITLE
Update Get-AzureADDirectoryRoleTemplate.md

### PR DESCRIPTION
**Pull request by mahmoudmsft**
Roletemplate "user account administrator" has been changed to "User Administrator"

>> from article mentioned by you (output of command "Get-AzureADDirectoryRoleTemplate")
`fe930be7-5e62-47db-91af-98c3a49a38b1 User Account Administrator`

>> running same command in my azure environment:
`fe930be7-5e62-47db-91af-98c3a49a38b1 User Administrator`

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[abb2725](https://github.com/mahmoudmsft/azure-docs-powershell-azuread/commits/abb2725aa719d795ba7add60710e659622a84caf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADDirectoryRoleTemplate.md](https://github.com/mahmoudmsft/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADDirectoryRoleTemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryroletemplate?view=azureadps-2.0&branch=pr-en-us-674) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107290607301660-674%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A41%3A13Z&ske=2021-08-04T03%3A46%3A13Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T06%3A03%3A29Z&se=2021-08-29T06%3A08%3A29Z&sr=b&sp=r&sig=4%2BUExfdCsGR6s3Nar97UlAUTeCEWZsWcHpgBXokfhAU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hello @mahmoudmsft, thanks for your contribution. This PR is created against the live branch. Kindly redo it against the master branch.

**Comment by mahmoudmsft** [comment]
@msewaweru done in master branch. thank you

**Comment by msewaweru** [comment]
@mahmoudmsft, still shows it is against the live branch. 
image

**Comment by mahmoudmsft** [comment]
Oh sorry, it's done now.

**Comment by msewaweru** [comment]
@CelesteDG , this is good to go.

**Comment by mahmoudmsft** [comment]
@msewaweru , how long it takes to be published in live version usually? i could see it's still not having the new change. thanks

**Comment by msewaweru** [comment]
@mahmoudmsft, sorry we are yet to merge this to live. We had some dependencies that we are yet to meet. Otherwise, it should normally be within the day after merge to master. I will let you know when this is done.

**Pull request merged**
