### PR TITLE
Update Get-AzureADDirectoryRole.md

### PR DESCRIPTION
**Pull request by jeevanbalanmanoj**
Company Administrator is an old role which got replaced with Global Administrator role. A customer has raised an issue with this. I also noticed that some of the other roles given were also outdated, fixed those as well

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[b34992f](https://github.com/jeevanbalanmanoj/azure-docs-powershell-azuread/commits/b34992f150edef97504c1e198459bdad1d1fa2f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md](https://github.com/jeevanbalanmanoj/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202104071710397676-594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O%2FSaHvcdh699ErsKu8bwyiuDQ4tb%2BNfpLINxQKGXfsk%3D&st=2021-04-07T17%3A06%3A32Z&se=2021-05-08T17%3A11%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jeevanbalanmanoj** [comment]
@billmath Can you please review these changes before they are merged?

**Comment by msewaweru** [comment]
Hi @jeevanbalanmanoj, thanks for your contribution. I however note that your PR has been created against the live and not master. Kindly redo and repost.

**Comment by msewaweru** [comment]
@jeevanbalanmanoj , I will go ahead and close this issue. I have created a new PR #662 that makes these changes against the master branch.

**Pull request closed without merging**
