### PR TITLE
Fill some missing Graph API data

### PR DESCRIPTION
**Pull request by mavaddat**
Filled in missing descriptions of cmdlet params from live Graph API docs [here](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta#consentprovidedforminor-values)

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[df7899b](https://github.com/mavaddat/azure-docs-powershell-azuread/commits/df7899b288daf8f00b5058ed01ea4089c7676953)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADUser.md](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUser.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202104220437198360-598%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=huCOUyM6zqkkJzzyaG%2FI1gAznFuHc0bxyUGeXUR2rIM%3D&st=2021-04-22T04%3A33%3A07Z&se=2021-05-23T04%3A38%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[41af957](https://github.com/mavaddat/azure-docs-powershell-azuread/commits/41af95787b349c679633c5b77e610829832df699)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADUser.md](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUser.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202104221651303357-598%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J6dmW548TPCzHsrjkJY0Lmzd5tU69JUzjmti45NsHNM%3D&st=2021-04-22T16%3A47%3A14Z&se=2021-05-23T16%3A52%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[ab6bc21](https://github.com/mavaddat/azure-docs-powershell-azuread/commits/ab6bc219d47e75e1fe579e34f90155daa8b09f21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADUser.md](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUser.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202104221708131742-598%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xl2QpcoHfdGjQdvoN2SM8b7YKGm3ZWNWevWt8%2Fx8EcA%3D&st=2021-04-22T17%3A03%3A59Z&se=2021-05-23T17%3A08%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[e150607](https://github.com/mavaddat/azure-docs-powershell-azuread/commits/e150607340bf88e0c210f58b363597f8e35c2568)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[3622a26](https://github.com/mavaddat/azure-docs-powershell-azuread/commits/3622a26652c2123db36ba9c44d964ac99ada67fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/Add-AzureADAdministrativeUnitMember.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADAdministrativeUnitMember.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADApplicationOwner.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADApplicationOwner.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADApplicationPolicy.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADApplicationPolicy.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADDeviceRegisteredOwner.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADDeviceRegisteredOwner.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADDeviceRegisteredUser.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADDeviceRegisteredUser.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADDirectoryRoleMember.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADDirectoryRoleMember.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADGroupMember.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADGroupMember.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADGroupOwner.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADGroupOwner.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADMSApplicationOwner.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADMSApplicationOwner.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADMSFeatureRolloutPolicyDirectoryObject.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADMSFeatureRolloutPolicyDirectoryObject.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADMSLifecyclePolicyGroup.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADMSLifecyclePolicyGroup.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADMSPrivilegedResource.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADMSPrivilegedResource.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADMSServicePrincipalDelegatedPermissionClassification.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADMSServicePrincipalDelegatedPermissionClassification.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADScopedRoleMembership.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADScopedRoleMembership.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADServicePrincipalOwner.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADServicePrincipalOwner.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADServicePrincipalPolicy.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Add-AzureADServicePrincipalPolicy.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Close-AzureADMSPrivilegedRoleAssignmentRequest.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Close-AzureADMSPrivilegedRoleAssignmentRequest.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Confirm-AzureADDomain.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Confirm-AzureADDomain.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Connect-AzureAD.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Connect-AzureAD.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Disconnect-AzureAD.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Disconnect-AzureAD.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Enable-AzureADDirectoryRole.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Enable-AzureADDirectoryRole.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnit.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnit.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnitMember.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnitMember.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplication.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplication.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationExtensionProperty.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationExtensionProperty.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationKeyCredential.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationKeyCredential.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationLogo.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationLogo.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationOwner.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationOwner.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationPasswordCredential.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationPasswordCredential.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationPolicy.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationPolicy.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyApplication.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyApplication.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyApplicationConnectorGroup.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyApplicationConnectorGroup.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnector.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnector.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnectorGroup.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnectorGroup.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnectorGroupMembers.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnectorGroupMembers.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnectorMemberOf.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationProxyConnectorMemberOf.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationServiceEndpoint.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationServiceEndpoint.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationSignInDetailedSummary.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationSignInDetailedSummary.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADApplicationSignInSummary.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADApplicationSignInSummary.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADAuditDirectoryLogs.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADAuditDirectoryLogs.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADAuditSignInLogs.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADAuditSignInLogs.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADContact.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADContact.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADContactDirectReport.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADContactDirectReport.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADContactManager.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADContactManager.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADContactMembership.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADContactMembership.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADContactThumbnailPhoto.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADContactThumbnailPhoto.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADContract.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADContract.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADCurrentSessionInfo.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADCurrentSessionInfo.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADDeletedApplication.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADDeletedApplication.yml) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADDevice.yml](https://github.com/mavaddat/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Get-AzureADDevice.yml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202104271934416491-598%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rpEY6QZpXzkMGdjvSchy%2BQgr2%2FqZvullafyfCCCAspw%3D&st=2021-04-27T19%3A30%3A36Z&se=2021-05-28T19%3A35%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hello @mavaddat, thanks for your contribution. Unfortunately you will have to redo this PR so that it is created against the master and not the live. Also, break the PR into smaller chunks so it makes the work of reviewing the changes much easier.

**Pull request merged**
