### PR TITLE
Added a note for PowerShell 7 incompatibility

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by msewaweru** [comment]
Fixes #760

**Comment by billmath** [comment]
Docs Build status updates of commit _[a9200c4](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/a9200c44677366cbb296c991ebbdb86bec62cc11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/install-adv2.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/powershell-7-update/docs-conceptual/azureadps-2.0/install-adv2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0&branch=pr-en-us-776) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202202080759449944-776%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T08%3A01%3A03Z&sr=b&sp=r&sig=vdeFS6TxeqFdvkFdKU4nUMeJRhoM4eLrBQNFikGaFlI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[c5af13f](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/c5af13fa7f52ddbd9e871de1145ee4a968e0f8e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/install-adv2.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/powershell-7-update/docs-conceptual/azureadps-2.0/install-adv2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0&branch=pr-en-us-776) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202202091217566064-776%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T12%3A19%3A20Z&sr=b&sp=r&sig=xihfAaaK6dpEOWaVSDeMHBttYnDBlFSmMlZr2JOuX2E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[9d3f84e](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/9d3f84ea7ba776281be27108137fe672634e9356)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/install-adv2.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/powershell-7-update/docs-conceptual/azureadps-2.0/install-adv2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0&branch=pr-en-us-776) (azureadps-2.0) | [Details](#user-content-db5d3e51df6d2f348b0b34f20777a84c-491b94be)

<a id="db5d3e51df6d2f348b0b34f20777a84c-491b94be"></a>
### [docs-conceptual/azureadps-2.0/install-adv2.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/powershell-7-update/docs-conceptual/azureadps-2.0/install-adv2.md)
 - **Line 7, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '08/02/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C11%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202202110635598507-776%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-14T06%3A37%3A19Z&sr=b&sp=r&sig=78jN%2FV3XaOq9Cf%2Fe5dBUr5Tr7kiNFAFt0yIDbyo6hmE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by hujiulin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by msewaweru** [comment]
@CelesteDG, please review this.

**Pull request merged**
