### PR TITLE
Fix new user example

### PR DESCRIPTION
**Pull request by gewarren**
Fixes https://github.com/MicrosoftDocs/feedback/issues/3318.

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[936de7f](https://github.com/gewarren/azure-docs-powershell-azuread/commits/936de7fb040785baf0f4cb6d09745b21a4382a53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADUser.md](https://github.com/gewarren/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/New-AzureADUser.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202012161912008921-543%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t3Vl%2BYr%2BGvpMHpYSk1S6Tj%2ByoizHQ5FYQdZ6%2FMUZiZs%3D&st=2020-12-16T19%3A07%3A48Z&se=2021-01-16T19%3A12%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by gewarren** [comment]
Was this supposed to go directly into the live branch? Just noticed that.

**Comment by sdwheeler** [comment]
Ouch. No it needs to go to master.

**Comment by gewarren** [comment]
I'm not sure why it went to live since this line is set to master: https://github.com/Azure/azure-docs-powershell-azuread/blob/26172c26858f98f4b17677a2647a1b84ac50b303/.openpublishing.publish.config.json#L17. But if you click edit on [the page](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduser?view=azureadps-2.0#example-1--create-a-user), it goes to live.

**Pull request merged**
