### PR TITLE
Update Get-AzureADDevice.md

### PR DESCRIPTION
**Pull request by Skatterbrainz**
Added examples 3 and 4

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[a1d5dfd](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/commits/a1d5dfdfa566d3d17f56b8e8319ee75f64834f99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADDevice.md](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADDevice.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddevice?view=azureadps-2.0&branch=pr-en-us-848) (azureadps-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202208151737306897-848/BuildReport?accessString=27b8c9f366fdad841732a3e8698feada28657a9579475be0d03cc5fa928a66ed).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Thanks @Skatterbrainz for your contribution. You however need to create the PR against the main branch instead of live as per policy. Please redo this and tag me for a review.

**Comment by Skatterbrainz** [comment]
I'm not sure how to redo the PR against the main branch.

**Comment by billmath** [comment]
Learn Build status updates of commit _[a1d5dfd](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/commits/a1d5dfdfa566d3d17f56b8e8319ee75f64834f99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Get-MsolDirSyncFeatures.md](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Get-MsolDirSyncFeatures.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/msonline/get-msoldirsyncfeatures?view=azureadps-1.0&branch=pr-en-us-848) (azureadps-1.0) |
[azureadps-2.0/AzureAD/Get-AzureADContact.md](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADContact.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/azuread/get-azureadcontact?view=azureadps-2.0&branch=pr-en-us-848) (azureadps-2.0) |
[azureadps-2.0/AzureAD/Get-AzureADDevice.md](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADDevice.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/azuread/get-azureaddevice?view=azureadps-2.0&branch=pr-en-us-848) (azureadps-2.0) |
[azureadps-2.0-preview/AzureAD/Set-AzureADPolicy.md](https://github.com/Skatterbrainz/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0-preview/AzureAD/Set-AzureADPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/azuread/set-azureadpolicy?view=azureadps-2.0-preview&branch=pr-en-us-848) (azureadps-2.0-preview) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202210260933484491-848/BuildReport?accessString=58d49e297933a2bd6baba4c84c881dc7d1b54d294a405d706c248d9b668c3a66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by msewaweru** [comment]
> I'm not sure how to redo the PR against the main branch.

Hi @Skatterbrainz, I have updated the base branch for you. To do this future, you can follow [these intsructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

**Pull request merged**
