### PR TITLE
Live

### PR DESCRIPTION
**Pull request by Ostars-eye**
@mattetti @bratsche @notlaforge @nickstenning @archerzz

### CODE REVIEW

**Comment by Ostars-eye** [comment]
- [ ] Retarget

**Comment by billmath** [comment]
Docs Build status updates of commit _[2905ae6](https://github.com/Azure/azure-docs-powershell-azuread/commits/2905ae6985c145ff1f03feae647707c575a61bdb)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202202091856344757-777%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T18%3A58%3A04Z&sr=b&sp=r&sig=Nn%2Bf8YctUOVQVxiUqFrLHjnGm6q%2FulXFxr7a%2ByKg2yE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Ostars-eye** [comment]
.patch

**Comment by Ostars-eye** [comment]
I'm Sorry

Maybe i Boke something

<https://1drv.ms/u/s!Aq9cH_l6PucrgP9LtzmEs84oDfjTSw>
[https://public.bl.files.1drv.com/y4mAqzyqhAXwuMnw7NqvMb7J41424RA870pbtOxA0SdiM70XntFr5n1eGfvt_0GDSKsWnrDMrjgJUATAYUxLmJvPdZuJpQtHl35mn5JEE3Ugoo31dUz1h4U-CenlOVTQHwoErNS2GZ_U4PJhYcvNnJbHvgr5v4WWTY4BdQrgaOxelan_CLhAcgCN1ZF3Z9Xd5w7?width=200&height=150&cropmode=center]
[https://outlook-1.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]2022-02-09 (2).png

________________________________
De: Bill Mathers ***@***.***>
Enviado: quarta-feira, 9 de fevereiro de 2022 16:58
Para: Azure/azure-docs-powershell-azuread ***@***.***>
Cc: Andre Ferraz ***@***.***>; Author ***@***.***>
Assunto: Re: [Azure/azure-docs-powershell-azuread] Live (PR #777)


Docs Build status updates of commit 2905ae6<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-docs-powershell-azuread%2Fcommits%2F2905ae6985c145ff1f03feae647707c575a61bdb&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N4iVXysgRjGCCFZij2cf%2FjJTepUMyFqgm%2BBMKSX%2BAkk%3D&reserved=0>:

⚠️ Validation status: warnings

For more details, please refer to the build report<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopbuilduserstoragepublic.blob.core.windows.net%2Freport%2F2022%255C2%255C9%255Ced7d034d-a56c-a713-9d51-730d2ba643e8%255CPullRequest%255C202202091856344757-777%255Cworkflow_report.html%3Fsv%3D2020-08-04%26se%3D2022-03-12T18%253A58%253A04Z%26sr%3Db%26sp%3Dr%26sig%3DNn%252Bf8YctUOVQVxiUqFrLHjnGm6q%252FulXFxr7a%252ByKg2yE%253D&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TSztzuv%2FoaFq1tO9rytJ0o%2FsqWOuorz453w0lDq%2Bt8k%3D&reserved=0>.

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions here<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fhelp%2Fonboard%2Fsso-troubleshooting%3Fbranch%3Dmain&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3ET2DguCtEAgZXehK9whRQlCFuvZYQkoEvRSM%2BhVqwY%3D&reserved=0> to re-authorize your GitHub account to Docs Build.

Note: Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the broken link report<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fops.microsoft.com%2F%23%2Frepos%2Fed7d034d-a56c-a713-9d51-730d2ba643e8%3FtabName%3Dbrokenlinks&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UyxWaSXHfTzkAJBwHDDZP%2BguuWlPHNuFf3YXeqvZ388%3D&reserved=0>.

Note: Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these instructions<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fhelp%2Fonboard%2Ffaq%3Fbranch%3Dmain%26tabs%3Dpr-validation-error-solution%23q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TVdpnWuUpt4oZ8G1%2FdJqbqdG1T9FnD5SjtazoSmc4XY%3D&reserved=0> to resolve them.

For any questions, please:

  *   Try searching the docs.microsoft.com contributor guides<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fhelp%2F%3Fbranch%3Dmain&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W9Vjtbe%2Fd4e0M8u62rbG3m7DN21o5g9ylD67iwmPHpY%3D&reserved=0>
  *   Post your question in the Docs support channel<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fchannel%2F19%253a7ecffca1166a4a3986fed528cf0870ee%2540thread.skype%2FGeneral%3FgroupId%3Dde9ddba4-2574-4830-87ed-41668c07a1ca%26tenantId%3D72f98bf-86f1-41af-91ab-2d7cd011db47&data=04%7C01%7C%7Ce265bd2212bf49d8147c08d9ebfe22f6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800299034241650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TEHrB59Z6NhPFEdA64AuGCb33YClYtzCKnNeqWHi%2BWo%3D&reserved=0>

**Pull request closed without merging**
