### PR TITLE
Better formatting of the PowerShell code

### PR DESCRIPTION
**Pull request by estruyf**
Updated the formatting of the PowerShell code. On the website the **New** keyword was removed from the `New-AzureADUser` cmdlet.

### CODE REVIEW

**Comment by RobdeJong** [comment]
Hi - is ```powershell the better way to mark a section to be displayed as <code> ?

**Comment by estruyf** [comment]
@RobdeJong no, that is just for letting your editor know the preferred syntax highlighting. 

The initial problem is something else, here is a screenshot of the issues: 

snip_20170406141647-update

In the first block of code, everything is on one line. So I changed that to a code block.

The second block with the `New-AzureADUser` cmdlet was defined just after the three backticks, so the editor thinks that `New` is the actual code language. By adding a linebreak that problem is resolved.

**Comment by RobdeJong** [comment]
@estruyf Excellent response, thanks! I have been struggling with the MD formatting of articles a bit - it seems that using a 4 spaces or a single backtick to indicate <code> doesn't work well here. Do we have some documentation of the MD formatting we can use here?

**Comment by estruyf** [comment]
@RobdeJong single `tick-back` is just for highlighting it in the current line. Code blocks are written with three tick-backs: https://help.github.com/articles/creating-and-highlighting-code-blocks/

Here is a useful doc page: https://help.github.com/articles/basic-writing-and-formatting-syntax/

**Comment by sankethka** [comment]
@estruyf An example cannot have more than one code block. Powershell engine doesn't accept it. The build was failing so I had to change to single tick.

**Comment by RobdeJong** [comment]
Hi - I was reading the doc links that @estruyf included, it doesn't mention anything about the PowerShell help engine MD syntax and requirements. Do we have these documented anywhere? What does \```powershell\ do exactly?

**Comment by TaraMeyer** [comment]
@RobdeJong  ``` followed by PowerShell indicates that the code in the block is PowerShell and should be formatted as such.  For example if the code block was to contain Java - it would be ```javascript - then the code.

**Comment by RobdeJong** [comment]
Thanks, @TaraMeyer . How is the formatting of a PowerShell block different from the generic \<Code> formatting?

**Comment by TaraMeyer** [comment]
@RobdeJong - the major difference is how it renders.  with the three ` followed by PowerShell - the text in the code block following the back ticks will "look" like the text would in a PowerShell console via the engine.  You'll find this mainly in the examples section of the MDs we support.  So the difference between the two is how each renders.

**Pull request merged**
