### PR TITLE
[Azure AD Preview] v2.0.2.138 new cmdlet documentation

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[3251d24](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/3251d2464afa38b206ff70f210b86adc9ea74e96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/add-azureadmscustomsecurityattributedefinitionallowedvalues?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSAttributeSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSAttributeSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsattributeset?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinition.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmscustomsecurityattributedefinition?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmscustomsecurityattributedefinitionallowedvalue?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSServicePrincipal.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSServicePrincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsserviceprincipal?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsuser?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSAttributeSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/New-AzureADMSAttributeSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsattributeset?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSCustomSecurityAttributeDefinition.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/New-AzureADMSCustomSecurityAttributeDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmscustomsecurityattributedefinition?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSAttributeSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSAttributeSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsattributeset?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinition.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmscustomsecurityattributedefinition?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmscustomsecurityattributedefinitionallowedvalue?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSServicePrincipal.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSServicePrincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsserviceprincipal?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsuser?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[mapping/groupMapping-2.0-preview.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/mapping/groupMapping-2.0-preview.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C1%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202111011336208000-718%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-02T13%3A37%3A25Z&sr=b&sp=r&sig=VvPGcHc5yEDrQGeyvQ5BJC%2FI8e%2Ba0lMzKbPr97iT0wA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[6b6e5fe](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/6b6e5fee25ce5f8878d4edb5e4416e6a016e6043)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/.vscode/settings.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/.vscode/settings.json) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/add-azureadmscustomsecurityattributedefinitionallowedvalues?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSAttributeSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSAttributeSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsattributeset?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinition.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmscustomsecurityattributedefinition?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmscustomsecurityattributedefinitionallowedvalue?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSServicePrincipal.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSServicePrincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsserviceprincipal?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsuser?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSAttributeSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/New-AzureADMSAttributeSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsattributeset?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSCustomSecurityAttributeDefinition.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/New-AzureADMSCustomSecurityAttributeDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmscustomsecurityattributedefinition?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSAttributeSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSAttributeSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsattributeset?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinition.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmscustomsecurityattributedefinition?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSCustomSecurityAttributeDefinitionAllowedValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmscustomsecurityattributedefinitionallowedvalue?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSServicePrincipal.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSServicePrincipal.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsserviceprincipal?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Set-AzureADMSUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/azureadps-2.0-preview/AzureAD/Set-AzureADMSUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsuser?view=azureadps-2.0-preview&branch=pr-en-us-718) (azureadps-2.0-preview) |
[mapping/groupMapping-2.0-preview.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/preview-v138-cmdlets/mapping/groupMapping-2.0-preview.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C1%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202111011401442020-718%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-02T14%3A02%3A57Z&sr=b&sp=r&sig=xg05Vfd18G84SsOyuSBok8mNYH1U7tZJ%2B4OnNCtuIks%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by rolyon — APPROVED** [review]

**Comment by rolyon** [comment]
Hi @msewaweru
This pull request is ready to be merged.
thanks

**Comment by msewaweru** [comment]
@CelesteDG, we now have the go ahead to merge this.

**Pull request merged**
