### PR TITLE
Create Get-AzureADMSAuthorizationPolicy.md

### PR DESCRIPTION
**Pull request by abhijeetsinha**

### CODE REVIEW

**Comment by qinezh** [comment]
Docs Build status updates of commit _[2c14ab8](https://github.com/Azure/azure-docs-powershell-azuread/commits/2c14ab8145af785592bf003127081bfc296a124c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C13%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202006130024212706-426%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aFdedo5FBFFZ525YTj1XLDLNRZ235TWK%2FFr61LmNqIc%3D&st=2020-06-13T00%3A21%3A57Z&se=2020-07-14T00%3A26%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by qinezh** [comment]
Docs Build status updates of commit _[bf7f608](https://github.com/Azure/azure-docs-powershell-azuread/commits/bf7f608979acb3d877b0eb3c27c4d4a5d8c10c35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Set-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/Set-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C13%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202006130034203603-426%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JmzF8mqEMfhEWXqpb4%2B9krnfU8qsCYwpYrpmZvScXMM%3D&st=2020-06-13T00%3A32%3A04Z&se=2020-07-14T00%3A37%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by prontohostau** [comment]
@abhijeetsinha 
I need a help to work with some group settings. I went to the article, but feedback section was empty. 
THe required function for me was - -MembershipRuleProcessingState "Paused". Does this command works/supported?

**Comment by abhijeetsinha** [comment]
@billmath , @curtand  - I also need to update the table of contents as I am adding two new cmdlets. Can you tell me which file to update?

**Comment by qinezh** [comment]
Docs Build status updates of commit _[ab2f892](https://github.com/Azure/azure-docs-powershell-azuread/commits/ab2f89271fabc594b036285eed8e54c790616aac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Set-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/Set-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202006222028233768-426%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m90OKkl8FGcSvrnYofplXS0blNXs3%2FaSxu9vo9%2FjnW8%3D&st=2020-06-22T20%3A26%3A17Z&se=2020-07-23T20%3A31%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by qinezh** [comment]
Docs Build status updates of commit _[d6fad83](https://github.com/Azure/azure-docs-powershell-azuread/commits/d6fad83b66c23521ae6032a10fe502c6c61fe6b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Set-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/Set-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |
[azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/abhijeetsinha-authzPolicy/azureadps-2.0-preview/AzureAD/Get-AzureADMSAuthorizationPolicy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202006222030572993-426%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZZu5VBPj%2Fz%2Fndm8CFdMM34QLIctI5RxuSde03kdzJmQ%3D&st=2020-06-22T20%3A29%3A36Z&se=2020-07-23T20%3A34%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
