### PR TITLE
Added an example and updated a parameter desc

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[c066ca1](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/c066ca19360a5c7512fe1f3063f92476598c6ab7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Set-MsolDomainFederationSettings.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/issue-688/azureadps-1.0/MSOnline/Set-MsolDomainFederationSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/set-msoldomainfederationsettings?view=azureadps-1.0&branch=pr-en-us-783) (azureadps-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202202221248525586-783%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T12%3A50%3A02Z&sr=b&sp=r&sig=R22H8r%2F9wAI2LBUqLarzYpqGprVnAWavjlIQ2usCAiw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Fixes #688.

**Comment by msewaweru** [comment]
@billmath , please review the changes I made on this cmdlet based on what we discussed.

**Comment by billmath** [comment]
#sign-off

**Comment by msewaweru** [comment]
@CelesteDG , please review this.

**Comment by fabnord** [comment]
@CelesteDG can you please review and merge?

**Pull request merged**
