### PR TITLE
Remove-AzureADServicePrincipalOwner - added an example for the cmdlet.

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by msewaweru** [comment]
@CelesteDG , please review this.

**Comment by billmath** [comment]
Docs Build status updates of commit _[303e6c4](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/303e6c4b5e17350d84c3284d4870b37056360455)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Remove-AzureADServicePrincipalOwner.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/remove-service-principal-owner/azureadps-2.0/AzureAD/Remove-AzureADServicePrincipalOwner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/remove-azureadserviceprincipalowner?view=azureadps-2.0&branch=pr-en-us-763) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201251105247556-763%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T11%3A06%3A41Z&sr=b&sp=r&sig=0yMhak170QV5aQZDXpsfeBU%2F%2FiCEQ%2FVB8FdJK4pg370%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[d872769](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/d872769706f27ce720c98043a04e8c559002ad27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Remove-AzureADServicePrincipalOwner.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/remove-service-principal-owner/azureadps-2.0/AzureAD/Remove-AzureADServicePrincipalOwner.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/remove-azureadserviceprincipalowner?view=azureadps-2.0&branch=pr-en-us-763) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201251107400243-763%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T11%3A08%3A54Z&sr=b&sp=r&sig=GsiDrhJ75ERlOXEXxYh7%2F8ltiqBQ2maD2AKaenSOC5g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by CelesteDG** [comment]
Thanks, @msewaweru - Merged

**Pull request merged**
