### PR TITLE
Update Get-MsolDomain.md

### PR DESCRIPTION
**Pull request by DisruptiveMind**
Update get by domain example parameter:

Get-MsolDomain `-Name` => `-DomainName`

### CODE REVIEW

**Comment by reepje123** [comment]
Why has this still not been merged?
I just closed my duplicate pull request for this. Even another newer one for the same issue exists..

**Comment by DisruptiveMind** [comment]
Duplicate here as well: https://github.com/Azure/azure-docs-powershell-azuread/pull/358

**Comment by DisruptiveMind** [comment]
thanks @reepje123 just referencing yours as well here: https://github.com/Azure/azure-docs-powershell-azuread/pull/379

Is there another step I am missing for this to get merged?

**Comment by billmath** [comment]
Hi @DisruptiveMind 

Per the [read me](https://github.com/Azure/azure-docs-powershell-azuread/blob/master/README.md) file:

Please be aware that if you have any updates to automatically generated reference content, you should create an issue and not a PR.  The issue will then be created into a bug and triaged accordingly.  We do this because the reference content must mirror the &#42;dll-help.xml file and subsequent updates to the reference content may overwrite any changes made through the repo.  Capturing it in the source code ensures that this does not occur.  Any PR with changes to automatically generated reference content will be closed.  

Automatically generated reference content is any of the content under this Reference node, such as [Get-AzureADUser](https://docs.microsoft.com/powershell/module/AzureAD/Get-AzureADUser?view=azureadps-2.0)

This only applies to reference content and not conceptual content.  Pull requests for changes to conceptual content are accepted and encouraged.  An example of the conceptual content is the [Overview](https://docs.microsoft.com/powershell/azure/active-directory/overview?view=azureadps-2.0) or a scenario such as [importing data](https://docs.microsoft.com/powershell/azure/active-directory/importing-data?view=azureadps-2.0).

Thank you!

Bill

**Pull request closed without merging**
