### PR TITLE
Davenew

### PR DESCRIPTION
**Pull request by davenew**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[8be525f](https://github.com/Azure/azure-docs-powershell-azuread/commits/8be525f069ea31452386662905ea33ffb642676d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-1.0/install-msonlinev1.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/docs-conceptual/azureadps-1.0/install-msonlinev1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/install-msonlinev1?view=azureadps-1.0&branch=pr-en-us-756) (azureadps-1.0) | [Details](#user-content-1eab8fee23c7030273d77a4a9fb3e043-e20ac2db)
[azureadps-2.0/toc.yml](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/azureadps-2.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/add-azureadapplicationowner?view=azureadps-2.0&branch=pr-en-us-756) (azureadps-2.0) | [Details](#user-content-6fc9c3913fdc3f0b785275896ec148b3-e20ac2db)
[azureadps-2.0-preview/toc.yml](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/azureadps-2.0-preview/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/add-azureadadministrativeunitmember?view=azureadps-2.0-preview&branch=pr-en-us-756) (azureadps-2.0-preview) | [Details](#user-content-b02ffb1e1c40f25a9c0b5d2a8eb585de-e20ac2db)
[azureadps-1.0/toc.yml](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/azureadps-1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/add-msoladministrativeunitmember?view=azureadps-1.0&branch=pr-en-us-756) (azureadps-1.0) | [Details](#user-content-1b96581cb0e466f86082bb3a86b4ee98-e20ac2db)

<a id="1eab8fee23c7030273d77a4a9fb3e043-e20ac2db"></a>
### [docs-conceptual/azureadps-1.0/install-msonlinev1.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/docs-conceptual/azureadps-1.0/install-msonlinev1.md)
 - **Line 91, Column 28**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/powershell/module/msonline/connect-msolservice?view=azureadps-1.0' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 91, Column 28**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/powershell/module/msonline/connect-msolservice?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 91, Column 28**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/powershell/module/msonline/connect-msolservice?view=azureadps-1.0. Otherwise, remove the view parameter.`````

<a id="6fc9c3913fdc3f0b785275896ec148b3-e20ac2db"></a>
### [azureadps-2.0/toc.yml](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/azureadps-2.0/toc.yml)
 - **Line 5, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#administrative-units' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 26, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-application-management' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 45, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-connector-management' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 66, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#applications' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 109, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#azuread' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 210, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#certificate-authorities' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 221, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#connect-to-your-directory' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 228, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contacts' in 'azureadps-2.0/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 247, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contracts' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 252, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#deleted-objects' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 257, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#devices' in 'azureadps-2.0/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 282, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 291, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-objects' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 296, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-roles' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 325, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#domains' in 'azureadps-2.0/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 344, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#extension-properties' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 349, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#groups' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 404, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#oauth2' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 411, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#policies' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 418, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#service-principals' in 'azureadps-2.0/AzureAD/index.yml'.`````
 - **Line 465, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#users' in 'azureadps-2.0/AzureAD/index.yml'.`````

<a id="b02ffb1e1c40f25a9c0b5d2a8eb585de-e20ac2db"></a>
### [azureadps-2.0-preview/toc.yml](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/azureadps-2.0-preview/toc.yml)
 - **Line 5, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#administrative-units' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 50, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 83, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-application-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 102, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#application-proxy-connector-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 123, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#applications' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 174, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#azureadpreview' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 251, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#certificate-authorities' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 262, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#connect-to-your-directory' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 271, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contacts' in 'azureadps-2.0-preview/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 290, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#contracts' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 295, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#custom-security-attributes' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 316, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#deleted-objects' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 329, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#devices' in 'azureadps-2.0-preview/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 354, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 363, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-auditing' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 370, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-objects' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 375, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-roles' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 390, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#directory-settings' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 403, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#domains' in 'azureadps-2.0-preview/AzureAD/index.yml', did you mean '#options'?`````
 - **Line 422, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#extension-properties' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 427, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#groups' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 482, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#identity-provider-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 493, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#oauth2' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 500, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#object-settings' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 511, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#policies' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 528, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#privileged-role-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 551, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#role-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 568, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#service-principals' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 623, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#staged-rollout' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 638, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#trust-framework-policy-management' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````
 - **Line 649, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#users' in 'azureadps-2.0-preview/AzureAD/index.yml'.`````

<a id="1b96581cb0e466f86082bb3a86b4ee98-e20ac2db"></a>
### [azureadps-1.0/toc.yml](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/azureadps-1.0/toc.yml)
 - **Line 5, Column 11**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#msonline' in 'azureadps-1.0/MSOnline/index.yml'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201172306285107-756%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T23%3A07%3A41Z&sr=b&sp=r&sig=38bGGXExquJhVQn4AGaAVxd7SFub1ZkN7QuL0JBShnQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Thanks @davenew for your contribution.

@CelesteDG , this is good to go.

**Comment by billmath** [comment]
Docs Build status updates of commit _[6446034](https://github.com/Azure/azure-docs-powershell-azuread/commits/6446034db4856680ad5aa3d3a989cf067d23981f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-1.0/install-msonlinev1.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/docs-conceptual/azureadps-1.0/install-msonlinev1.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/install-msonlinev1?view=azureadps-1.0&branch=pr-en-us-756) (azureadps-1.0) | [Details](#user-content-1eab8fee23c7030273d77a4a9fb3e043-e3588910)

<a id="1eab8fee23c7030273d77a4a9fb3e043-e3588910"></a>
### [docs-conceptual/azureadps-1.0/install-msonlinev1.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/docs-conceptual/azureadps-1.0/install-msonlinev1.md)
 - **Line 89, Column 28**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/connect-msolservice?view=azureadps-1.0' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 89, Column 28**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/msonline/connect-msolservice?view=azureadps-1.0. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201211854359981-756%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T18%3A55%3A56Z&sr=b&sp=r&sig=pf7vrLp4Yxt9M3QKi9NWsskwY%2BA4Z8NrAEq8LpGcg%2FI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by CelesteDG** [comment]
Thank you very much, @davenew - Thank you for your contribution. Let me remove the version from that URL. For our part, I just noted that it had the locale (en-us) and we typically do not include that in our URLs.

**Comment by billmath** [comment]
Docs Build status updates of commit _[dc0fb03](https://github.com/Azure/azure-docs-powershell-azuread/commits/dc0fb0361ba90c7cef1292147079312288f07b6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-1.0/install-msonlinev1.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/docs-conceptual/azureadps-1.0/install-msonlinev1.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/install-msonlinev1?view=azureadps-1.0&branch=pr-en-us-756) (azureadps-1.0) | [Details](#user-content-1eab8fee23c7030273d77a4a9fb3e043-7ad6a3fe)

<a id="1eab8fee23c7030273d77a4a9fb3e043-7ad6a3fe"></a>
### [docs-conceptual/azureadps-1.0/install-msonlinev1.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/davenew/docs-conceptual/azureadps-1.0/install-msonlinev1.md)
 - **Line 89, Column 28**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/powershell/module/msonline/connect-msolservice' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202201211909413477-756%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T19%3A11%3A24Z&sr=b&sp=r&sig=2qAmSTEtK%2BK%2BsHSu5%2F8Jnpuyy2Eo1KAE8qgi5HBzJ7I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
