### PR TITLE
TOC update for new cmdlets

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[d657653](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/d657653a22b60dbcfed51ff106a29f4a974ed483)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[mapping/groupMapping-2.0-preview.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/new-cmdlets-toc-update/mapping/groupMapping-2.0-preview.json) | :white_check_mark:Succeeded | |
[mapping/groupMapping-2.0.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/new-cmdlets-toc-update/mapping/groupMapping-2.0.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109031526547001-705%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RfOmi1IGgIxphuRBFcgqbDYUKIeduyXzc8%2BKdBdCsno%3D&st=2021-09-03T15%3A22%3A55Z&se=2021-10-04T15%3A27%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[2cc36ca](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/2cc36ca86f86a97264d4ba1fa0fc22d3601e1e46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[mapping/groupMapping-2.0-preview.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/new-cmdlets-toc-update/mapping/groupMapping-2.0-preview.json) | :white_check_mark:Succeeded | |
[mapping/groupMapping-2.0.json](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/new-cmdlets-toc-update/mapping/groupMapping-2.0.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109070823067878-705%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RjG9JLBtL41XHL%2Fz1vZj6QmHvbvdHjJ9kkYCZLWhU%2BQ%3D&st=2021-09-07T08%3A19%3A28Z&se=2021-10-08T08%3A24%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
@CelesteDG, please review this.

**Comment by CelesteDG** [comment]
HI @msewaweru - LGTM. Is this ready to go?

**Pull request merged**
