### PR TITLE
Update New-AzureADMSConditionalAccessPolicy.md

### PR DESCRIPTION
**Pull request by mukeshk-ms**
Added an example demonstrating "Filter for Devices" CA policy and fixed indentation

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[3515bd5](https://github.com/mukeshk-ms/azure-docs-powershell-azuread/commits/3515bd5e7c30a49c25b6a7861894275fc2f86483)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSConditionalAccessPolicy.md](https://github.com/mukeshk-ms/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/New-AzureADMSConditionalAccessPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsconditionalaccesspolicy?view=azureadps-2.0&branch=pr-en-us-811) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202204221602333751-811%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T16%3A03%3A28Z&sr=b&sp=r&sig=5sziAfgEwQFVgyicZDkYZqJjpAhn5XoVbaEQwfWAgk0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hi @mukeshk-ms, thanks for your contribution. I'm experiencing an error in the new example you have added.
This query returns an error  as below. 
`$conditions.Devices = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessDevicesCondition`

image.

This could be because the `$conditions` variable has the following properties of which devices is not one of them.

image

Could you could use .plarforms instead of .devices? This will in turn require that the subsequent variables are updated.

**Comment by msewaweru** [comment]
Hi @mukeshk-ms, thanks for your contribution. I'm experiencing an error in the new example you have added.
This query returns an error  as below. 
`$conditions.Devices = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessDevicesCondition`

image.

This could be because the `$conditions` variable has the following properties of which devices is not one of them.

image

Could you could use .plarforms instead of .devices? This will in turn require that the subsequent variables are updated.

**Comment by msewaweru** [comment]
Hi @mukeshk-ms, I got to move the new example you added to the Azure AD Preview module in PR #826. Thanks for your contribution.

**Pull request closed without merging**
