### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by BartekPog**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[d1655ae](https://github.com/BartekPog/azure-docs-powershell-azuread/commits/d1655ae75a0d9d278d194f477dcf1c3184b9a6e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADUserLicenseDetail.md](https://github.com/BartekPog/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Get-AzureADUserLicenseDetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduserlicensedetail?view=azureadps-2.0&branch=pr-en-us-712) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C10%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109100937389613-712%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=obRhnHilhay226777d6dFndPGf3bI2fyGNVZEnNQFW0%3D&st=2021-09-10T09%3A33%3A42Z&se=2021-10-11T09%3A38%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hello @BartekPog, thanks for your contribution. Please redo your PR with the base branch as master instead live as per the policy.

**Review by WingsBrokenAngel — APPROVED** [review]
It makes sense.

**Review by WingsBrokenAngel — CHANGES_REQUESTED** [review]
Merge to Master branch, please.

**Comment by msewaweru** [comment]
@CelesteDG, this is good to go.

**Pull request merged**
