### PR TITLE
Update Set-MsolPasswordPolicy.md

### PR DESCRIPTION
**Pull request by pfsantosaad**
update to master as requested by @msewaweru

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[9d8854f](https://github.com/pfsantosaad/azure-docs-powershell-azuread/commits/9d8854fb34e9150514ceeaf5a839ceb554f272fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Set-MsolPasswordPolicy.md](https://github.com/pfsantosaad/azure-docs-powershell-azuread/blob/patch-3/azureadps-1.0/MSOnline/Set-MsolPasswordPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/set-msolpasswordpolicy?view=azureadps-1.0&branch=pr-en-us-702) (azureadps-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109010831257918-702%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5e7bdcbWAv50wRYBJh9m3%2B5RItQDZgb2lGKhEhlBPu4%3D&st=2021-09-01T08%3A27%3A33Z&se=2021-10-02T08%3A32%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[9d8854f](https://github.com/pfsantosaad/azure-docs-powershell-azuread/commits/9d8854fb34e9150514ceeaf5a839ceb554f272fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Set-MsolPasswordPolicy.md](https://github.com/pfsantosaad/azure-docs-powershell-azuread/blob/patch-3/azureadps-1.0/MSOnline/Set-MsolPasswordPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/set-msolpasswordpolicy?view=azureadps-1.0&branch=pr-en-us-702) (azureadps-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109031421374796-702%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rkRPwiaEFKKA3OcTshIGa%2Fjh906TCw%2B7NA47berhENs%3D&st=2021-09-03T14%3A17%3A39Z&se=2021-10-04T14%3A22%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
@pfsantosaad , there is an action pending for you here

> [CLA assistant check](https://cla.opensource.microsoft.com/Azure/azure-docs-powershell-azuread?pullRequest=702)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-docs-powershell-azuread?pullRequest=702) before we can accept your contribution.
> 
> ❌ pfsantosaad [sign now](https://cla.opensource.microsoft.com/Azure/azure-docs-powershell-azuread?pullRequest=702)
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-docs-powershell-azuread?pullRequest=702) it.

**Comment by pfsantosaad** [comment]
Completed now @msewaweru Thanks

**Pull request merged**
