### PR TITLE
Update Set-AzureADUserThumbnailPhoto.md

### PR DESCRIPTION
**Pull request by dvandenburgh**
Fix spelling errors in example description

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[9b50f05](https://github.com/dvandenburgh/azure-docs-powershell-azuread/commits/9b50f057935361c450bd59c0f495d400fdf6a02e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADUserThumbnailPhoto.md](https://github.com/dvandenburgh/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUserThumbnailPhoto.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202103222101303423-582%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lyLn23xetroyBHTyqsc%2Brlg5yFVllScomuKaa1IaGqU%3D&st=2021-03-22T20%3A57%3A25Z&se=2021-04-22T21%3A02%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[f5a75fb](https://github.com/dvandenburgh/azure-docs-powershell-azuread/commits/f5a75fb909a654857f68e26f6bd92f5d16793585)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Get-MsolAdministrativeUnitMember.md](https://github.com/dvandenburgh/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Get-MsolAdministrativeUnitMember.md) | :white_check_mark:Succeeded | |
[azureadps-1.0/MSOnline/Set-MsolAdministrativeUnit.md](https://github.com/dvandenburgh/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Set-MsolAdministrativeUnit.md) | :white_check_mark:Succeeded | |
[azureadps-1.0/MSOnline/Set-MsolDeviceRegistrationServicePolicy.md](https://github.com/dvandenburgh/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Set-MsolDeviceRegistrationServicePolicy.md) | :white_check_mark:Succeeded | |
[azureadps-2.0/AzureAD/Set-AzureADUserThumbnailPhoto.md](https://github.com/dvandenburgh/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUserThumbnailPhoto.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202103241409277037-582%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qajS58p1uWygaLD1O47IWoMKRJckHFCHVq3W%2F8zzYQY%3D&st=2021-03-24T14%3A05%3A23Z&se=2021-04-24T14%3A10%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[1b62db3](https://github.com/dvandenburgh/azure-docs-powershell-azuread/commits/1b62db394bbee2f2fdc335d7b79109c80892eccd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADUserThumbnailPhoto.md](https://github.com/dvandenburgh/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUserThumbnailPhoto.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202103241459041383-582%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M%2F8iX7qL8gctRrtazqwyce63TzR5gmfNylcKC4rpkwM%3D&st=2021-03-24T14%3A54%3A56Z&se=2021-04-24T14%3A59%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hi @dvandenburgh, this has already been done https://github.com/Azure/azure-docs-powershell-azuread/pull/613. Proceeding to close this.

**Pull request closed without merging**
