### PR TITLE
Overhaul user and group app role assignment cmdlets

### PR DESCRIPTION
**Pull request by psignoret**
Changes parameter ordering to a logical order, fixes examples for `New-AzureADUserAppRoleAssignemnt`, adds equivalent examples for `New-AzureADGroupAppRoleAssignment`.

### CODE REVIEW

**Comment by TaraMeyer** [comment]
@RobdeJong, @VinceSmith  - is this pr ok to merge?  There are syntax changes and I will need your dign off before merging.  Thanks!

**Comment by TaraMeyer** [comment]
@RobdeJong - is this pr ok to merge?

**Comment by RobdeJong** [comment]
This pr looks good.

**Comment by TaraMeyer** [comment]
@RobdeJong  thank you- merging to master now.

**Pull request merged**
