### PR TITLE
Filled up the missing descriptions

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[26a1db2](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/26a1db2dde18ee3030e955e4e68dc2396d0210a9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[26a1db2](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/26a1db2dde18ee3030e955e4e68dc2396d0210a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/New-AzureADPrivilegedRoleAssignment.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/privileged-role-work/azureadps-2.0-preview/AzureAD/New-AzureADPrivilegedRoleAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadprivilegedroleassignment?view=azureadps-2.0-preview&branch=pr-en-us-668) (azureadps-2.0-preview) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107271640427476-668%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A44%3A52Z&ske=2021-08-02T02%3A49%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T16%3A36%3A38Z&se=2021-08-27T16%3A41%3A38Z&sr=b&sp=r&sig=CQ6GT7gIhBX%2Feoaf3KIfeFPhT%2BSNwznp7SU6sJI2hgY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[f523cf5](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/f523cf5aa6f8028053e3e33d6363a4cd99dc055e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0-preview/AzureAD/Get-AzureADPrivilegedRole.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/privileged-role-work/azureadps-2.0-preview/AzureAD/Get-AzureADPrivilegedRole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadprivilegedrole?view=azureadps-2.0-preview&branch=pr-en-us-668) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/Get-AzureADPrivilegedRoleAssignment.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/privileged-role-work/azureadps-2.0-preview/AzureAD/Get-AzureADPrivilegedRoleAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureadprivilegedroleassignment?view=azureadps-2.0-preview&branch=pr-en-us-668) (azureadps-2.0-preview) |
[azureadps-2.0-preview/AzureAD/New-AzureADPrivilegedRoleAssignment.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/privileged-role-work/azureadps-2.0-preview/AzureAD/New-AzureADPrivilegedRoleAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadprivilegedroleassignment?view=azureadps-2.0-preview&branch=pr-en-us-668) (azureadps-2.0-preview) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C29%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107290749118312-668%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A50%3A39Z&ske=2021-08-04T03%3A55%3A39Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-29T07%3A45%3A10Z&se=2021-08-29T07%3A50%3A10Z&sr=b&sp=r&sig=k5bsMe37nISDW%2Bgx%2FvPip78dayIzmJkGqwsLsm%2BZmD4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
This set of cmdlets have been confirmed to be deprecated. Closing this.

**Pull request closed without merging**
