### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by ndsimpson**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[d4d6fdc](https://github.com/ndsimpson/azure-docs-powershell-azuread/commits/d4d6fdc69cb4fa1517a541a55140cf14a532edb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADUser.md](https://github.com/ndsimpson/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/set-azureaduser?view=azureadps-2.0&branch=pr-en-us-711) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109091906167719-711%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=oyuGZk4R%2BaKj1VuJUQDg8vsfmkK0qcUGoCZ1NfXx4vU%3D&st=2021-09-09T19%3A02%3A17Z&se=2021-10-10T19%3A07%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hello @BartekPog, thanks for your contribution. Please redo your PR with the base branch as master instead live as per the policy.

**Review by WingsBrokenAngel — APPROVED** [review]
It makes sense.

**Comment by msewaweru** [comment]
Closing this. Issue has since been resolved in [this commit](https://github.com/Azure/azure-docs-powershell-azuread/commit/ff5fbc4e05dc0244211559d4373efccdfcee7fac#diff-6abf9dc31a4bf87962210b85b2de6904ce4cff15c30bf8a4fc918717301c4f4c).

**Pull request closed without merging**
