### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by LeandroRRocha**
added deprecation date and link to the most up to date information on the blog

### CODE REVIEW

**Comment by billmath** [comment]
Learn Build status updates of commit _[8c18b40](https://github.com/LeandroRRocha/azure-docs-powershell-azuread/commits/8c18b4036217f386481e972d6b39b644ba138c33)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/overview.md](https://github.com/LeandroRRocha/azure-docs-powershell-azuread/blob/patch-1/docs-conceptual/azureadps-2.0/overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/azure/active-directory/overview?view=azureadps-2.0&branch=pr-en-us-872) (azureadps-2.0) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202211301944559769-872/BuildReport?accessString=4c60270f7d932ef1c40982159720dee59a661fad410f553bd56ba21f0ea9c78a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by LeandroRRocha** [comment]
Hi @msewaweru,  

official link: 
https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/microsoft-entra-change-announcements-september-2022-train/ba-p/2967454

PowerShell deprecation 

As we continue to support your migration efforts, we'll be extending the planned deprecation date of the three PowerShell Modules (Azure AD, Azure AD Preview, and MS Online) to June 30, 2023. The three modules will continue to work with minimal investment, apart from security updates. Depending on the status of Azure AD API, some cmdlets might stop working after June 30, 2023. The Microsoft Graph PowerShell SDK continues to be where all our current and future PowerShell investments are being made, and we encourage you to continue migrating to Microsoft Graph PowerShell SDK. We're also working on tools and documentation for migrating existing scripts and PowerShell processes reliant on the Azure AD Graph and MSOnline module to the Microsoft Graph PowerShell SDK. Check out more information at [Find Azure AD and MSOnline cmdlets in Microsoft Graph PowerShell | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0) and [Migrate from Azure AD PowerShell to the Microsoft Graph PowerShell SDK. | Microsoft Docs](https://docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0).

**Comment by LeandroRRocha** [comment]
The latest info is here: https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-change-management-simplified/ba-p/2967456

We [stated before ](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/automate-and-manage-azure-ad-tasks-at-scale-with-the-microsoft/ba-p/1942489)that if you’re using the Azure AD PowerShell or MSOnline PowerShell modules to manage Azure AD, we encourage you to try the Microsoft Graph PowerShell SDK. The Microsoft Graph PowerShell SDK continues to be where all our current and future PowerShell investments are being made. In light of the announcement to not turn off the Azure AD Graph API on June 30th, our goal is to also provide guidance and tools for migrating existing scripts and PowerShell processes, reliant on the Azure AD Graph API and MSOnline module, to the Microsoft Graph PowerShell SDK. This is due to the planned deprecation of the two PowerShell modules (MSOL & AAD) after December 2022. Check out more information [here](https://docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-beta) and [here](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq).

**Comment by msewaweru** [comment]
Thanks @LeandroRRocha for sharing. Please change the base branch of this PR to main instead of live.

**Comment by msewaweru** [comment]
@CelesteDG, this is ready to merge.

**Pull request merged**
