### PR TITLE
Fix content

### PR DESCRIPTION
**Pull request by ShintakuNobuhiro**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[18e54b3](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/commits/18e54b3971f26067dba735bc10ceb77f04c72c9d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADMSGroup.md](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADMSGroup.md) | :x:Error | | [Details](#user-content-e2fa54df-acf2ccfa)
[azureadps-2.0/AzureAD/index.yml](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/index.yml) | :warning:Warning | | [Details](#user-content-b6af1b45-acf2ccfa)

<a id="e2fa54df-acf2ccfa"></a>
### [azureadps-2.0/AzureAD/Set-AzureADMSGroup.md](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADMSGroup.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/ar3u-s/azureadps-2.0/AzureAD/Set-AzureADMSGroup.md:76:(340) '```yaml
Type: String

=======
Parameter Sets: ...'
 Invalid yaml: expected simple key-value pairs, please try to use PlatyPS validate the content
`````

<a id="b6af1b45-acf2ccfa"></a>
### [azureadps-2.0/AzureAD/index.yml](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/index.yml)
 - **Line 97, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Remove-AzureADMSServicePrincipalDelegatedPermissionClassification'.`````
 - **Line 100, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADMSApplication'.`````
 - **Line 106, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADMSPermissionGrantConditionSet'.`````
 - **Line 112, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Remove-AzureADTrustedCertificateAuthority'.`````
 - **Line 151, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADTenantDetail'.`````
 - **Line 172, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADDomain'.`````
 - **Line 201, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADGroup'.`````
 - **Line 202, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADMSGroup'.`````
 - **Line 207, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Remove-AzureADOAuth2PermissionGrant'.`````
 - **Line 215, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Get-AzureADServicePrincipalKeyCredential'.`````
 - **Line 250, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Remove-AzureADUser'.`````
 - **Line 258, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADUserExtension'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202012080153469835-536%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qbn9Bw8h23c3te7UJ744fFg7zquLIpNo1w0SBBQdzVg%3D&st=2020-12-08T01%3A49%3A38Z&se=2021-01-08T01%3A54%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ShintakuNobuhiro** [comment]
@billmath The article is broken. I'd like to fix it quickly, how can I merge it?

**Comment by billmath** [comment]
Docs Build status updates of commit _[fa2c4ce](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/commits/fa2c4ce68f7875648cfea164fef6089cec1ff046)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Set-AzureADMSGroup.md](https://github.com/ShintakuNobuhiro/azure-docs-powershell-azuread/blob/patch-1/azureadps-2.0/AzureAD/Set-AzureADMSGroup.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202012080201443105-536%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K1ie8nNAxXAA6wIV0xxAGcz092FBZc%2FZQka2Hz3i2zA%3D&st=2020-12-08T01%3A57%3A34Z&se=2021-01-08T02%3A02%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Hi @ShintakuNobuhiro 

Per the read me file:

Please be aware that if you have any updates to automatically generated reference content, you should create an issue and not a PR. The issue will then be created into a bug and triaged accordingly. We do this because the reference content must mirror the *dll-help.xml file and subsequent updates to the reference content may overwrite any changes made through the repo. Capturing it in the source code ensures that this does not occur. Any PR with changes to automatically generated reference content will be closed.

Automatically generated reference content is any of the content under this Reference node, such as Get-AzureADUser

This only applies to reference content and not conceptual content. Pull requests for changes to conceptual content are accepted and encouraged. An example of the conceptual content is the Overview or a scenario such as importing data.

Thank you!

Bill

**Pull request closed without merging**
