### PR TITLE
Added a noted under the ClientApplicationIds parameter

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[6bfad9d](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/6bfad9d5c30127a0e2a8d13b6f5ab34477a23e67)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :x:Error | | [Details](#user-content-c0ac00977a1bc5486ea9a6a3750a2d7d-49a0c79b)
[azureadps-2.0-preview/AzureAD/New-AzureADMSGroupLifecyclePolicy.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSGroupLifecyclePolicy.yml) | :x:Error | | [Details](#user-content-8db045eb2d91fb10c22cdcb1c2ac6912-49a0c79b)
[azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :x:Error | | [Details](#user-content-a05f14a7e1acb9c8e29b59db54d3d123-49a0c79b)
[azureadps-2.0-preview/AzureAD/Remove-AzureADExternalDomainFederation.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Remove-AzureADExternalDomainFederation.yml) | :x:Error | | [Details](#user-content-a706a720b240f753633993b832936a0b-49a0c79b)
[azureadps-2.0/AzureAD/index.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/index.yml) | :warning:Warning | | [Details](#user-content-37bfae49af1a8a6b2e01cf868c49bb89-49a0c79b)
[azureadps-2.0-preview/AzureAD/Confirm-AzureADDomain.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Confirm-AzureADDomain.yml) | :warning:Warning | | [Details](#user-content-8961500e5c467e07773b510780c62e0d-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnit.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnit.yml) | :warning:Warning | | [Details](#user-content-62338f1b8ca1fda13dea2e2a8127bd4c-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADApplication.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADApplication.yml) | :warning:Warning | | [Details](#user-content-de4b4d9b933d5f0ad6bc2b1808123a66-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADDevice.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADDevice.yml) | :warning:Warning | | [Details](#user-content-8b3f15f268823a3fa4867193ccde160d-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADDirectorySetting.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADDirectorySetting.yml) | :warning:Warning | | [Details](#user-content-22ba50282ff19381e52d9dfd05579d60-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADDomain.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADDomain.yml) | :warning:Warning | | [Details](#user-content-50263d2aaf684551175dcc266498c528-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADGroup.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADGroup.yml) | :warning:Warning | | [Details](#user-content-4336cb805e8dd1af728128624706fccc-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADObjectSetting.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADObjectSetting.yml) | :warning:Warning | | [Details](#user-content-b491eec965d07f630cf4f1e1a84169a1-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADPolicy.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADPolicy.yml) | :warning:Warning | | [Details](#user-content-5a5c664523394a82803e58434eb37e6a-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipal.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipal.yml) | :warning:Warning | | [Details](#user-content-05f14602cfb5762378b2c2ba70b90d93-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalKeyCredential.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalKeyCredential.yml) | :warning:Warning | | [Details](#user-content-2a309fe0fe1787ac369aa030523e63be-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalPasswordCredential.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalPasswordCredential.yml) | :warning:Warning | | [Details](#user-content-3139be1aea3257ab6586443d4f5c8a4c-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADTrustedCertificateAuthority.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADTrustedCertificateAuthority.yml) | :warning:Warning | | [Details](#user-content-2c4c47c466eece4ed632469cdb50ba93-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADUser.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUser.yml) | :warning:Warning | | [Details](#user-content-92c58621afccaf11294bab83091ec8fb-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADUserAppRoleAssignment.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUserAppRoleAssignment.yml) | :warning:Warning | | [Details](#user-content-52896de713ac06ee23a68c322f9dcf1b-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADUserExtension.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUserExtension.yml) | :warning:Warning | | [Details](#user-content-af53cda2bfc0165b2a4864830ac2fb68-49a0c79b)
[azureadps-2.0-preview/AzureAD/Get-AzureADUserManager.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUserManager.yml) | :warning:Warning | | [Details](#user-content-5385535f10f673b12f428b7b75040434-49a0c79b)
[azureadps-2.0-preview/AzureAD/index.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/index.yml) | :warning:Warning | | [Details](#user-content-a8b3ad7718c29863c50896dfc038c98d-49a0c79b)
[azureadps-2.0-preview/AzureAD/New-AzureADAdministrativeUnit.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADAdministrativeUnit.yml) | :warning:Warning | | [Details](#user-content-4d9c06feacc38baef587df75d71178ed-49a0c79b)
[azureadps-2.0-preview/AzureAD/New-AzureADApplication.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADApplication.yml) | :warning:Warning | | [Details](#user-content-fb8301d34901b13135ce32a993af030b-49a0c79b)

This comment lists only the first 25 files in the pull request.
<a id="c0ac00977a1bc5486ea9a6a3750a2d7d-49a0c79b"></a>
### [azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md)
 - **Line 0, Column 0**: **[Error: MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: C:/LocalRun/W/g3gw-s/azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md:163:(181) '>[!NOTE]
>There is a hard limit of 100 Applicatio...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="8db045eb2d91fb10c22cdcb1c2ac6912-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/New-AzureADMSGroupLifecyclePolicy.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSGroupLifecyclePolicy.yml)
 - **Line 1, Column 1**: **[Error: schema-not-found]** `````Unknown schema ''.`````

<a id="a05f14a7e1acb9c8e29b59db54d3d123-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md)
 - **Line 0, Column 0**: **[Error: MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: C:/LocalRun/W/g3gw-s/azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md:163:(181) '>[!NOTE]
>There is a hard limit of 100 Applicatio...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="a706a720b240f753633993b832936a0b-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Remove-AzureADExternalDomainFederation.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Remove-AzureADExternalDomainFederation.yml)
 - **Line 1, Column 1**: **[Error: schema-not-found]** `````Unknown schema ''.`````

<a id="37bfae49af1a8a6b2e01cf868c49bb89-49a0c79b"></a>
### [azureadps-2.0/AzureAD/index.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/index.yml)
 - **Line 169, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADMSRoleDefinition'.`````
 - **Line 218, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'AzureAD.Set-AzureADMSAuthorizationPolicy'.`````

<a id="8961500e5c467e07773b510780c62e0d-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Confirm-AzureADDomain.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Confirm-AzureADDomain.yml)
 - **Line 14, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADDomain.yml'.`````

<a id="62338f1b8ca1fda13dea2e2a8127bd4c-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnit.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADAdministrativeUnit.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADAdministrativeUnit.yml'.`````

<a id="de4b4d9b933d5f0ad6bc2b1808123a66-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADApplication.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADApplication.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADApplication.yml'.`````

<a id="8b3f15f268823a3fa4867193ccde160d-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADDevice.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADDevice.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADDevice.yml'.`````

<a id="22ba50282ff19381e52d9dfd05579d60-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADDirectorySetting.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADDirectorySetting.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADDirectorySetting.yml'.`````

<a id="50263d2aaf684551175dcc266498c528-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADDomain.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADDomain.yml)
 - **Line 14, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADDomain.yml'.`````

<a id="4336cb805e8dd1af728128624706fccc-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADGroup.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADGroup.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADGroup.yml'.`````

<a id="b491eec965d07f630cf4f1e1a84169a1-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADObjectSetting.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADObjectSetting.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADObjectSetting.yml'.`````

<a id="5a5c664523394a82803e58434eb37e6a-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADPolicy.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADPolicy.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADPolicy.yml'.`````

<a id="05f14602cfb5762378b2c2ba70b90d93-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipal.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipal.yml)
 - **Line 10, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Remove-AzureADServicePrincipal.yml'.`````
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADServicePrincipal.yml'.`````

<a id="2a309fe0fe1787ac369aa030523e63be-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalKeyCredential.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalKeyCredential.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Remove-AzureADServicePrincipalKeyCredential.yml'.`````

<a id="3139be1aea3257ab6586443d4f5c8a4c-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalPasswordCredential.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADServicePrincipalPasswordCredential.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Remove-AzureADServicePrincipalPasswordCredential.yml'.`````

<a id="2c4c47c466eece4ed632469cdb50ba93-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADTrustedCertificateAuthority.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADTrustedCertificateAuthority.yml)
 - **Line 8, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './New-AzureADTrustedCertificateAuthority.yml'.`````
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADTrustedCertificateAuthority.yml'.`````

<a id="92c58621afccaf11294bab83091ec8fb-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADUser.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUser.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADUser.yml'.`````

<a id="52896de713ac06ee23a68c322f9dcf1b-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADUserAppRoleAssignment.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUserAppRoleAssignment.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Remove-AzureADUserAppRoleAssignment.yml'.`````

<a id="af53cda2bfc0165b2a4864830ac2fb68-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADUserExtension.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUserExtension.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADUserExtension.yml'.`````

<a id="5385535f10f673b12f428b7b75040434-49a0c79b"></a>
### [azureadps-2.0-preview/AzureAD/Get-AzureADUserManager.yml](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/Get-AzureADUserManager.yml)
 - **Line 10, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './Set-AzureADUserManager.yml'.`````

This comment lists only the first 25 errors (including error/warning/suggestion) in the pull request.
For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202208181551041797-850/BuildReport?accessString=3a76c6f1ce0997a770b0cd75f685d4ed691bed07427d75e9d59a613af8e0710f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[0445616](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/0445616c5e4ad65d80fa6f623f4f824e48cee044)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmspermissiongrantconditionset?view=azureadps-2.0&branch=pr-en-us-850) (azureadps-2.0) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmspermissiongrantconditionset?view=azureadps-2.0-preview&branch=pr-en-us-850) (azureadps-2.0-preview) |
[azureadps-2.0-preview/debug.log](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/debug.log) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202208181555594135-850/BuildReport?accessString=ac6b860155a1dbc6a35f902b3b014aac2b30540efb931866d19fdeea28dfe3c2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
@timayabi2020, please merge this for me.

**Comment by msewaweru** [comment]
@mwongerapk, this is now ready for your review and merging.

**Comment by billmath** [comment]
Docs Build status updates of commit _[dafc095](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/dafc0954acfe62f9a34bbf5100f4d90073e7e708)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmspermissiongrantconditionset?view=azureadps-2.0&branch=pr-en-us-850) (azureadps-2.0) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmspermissiongrantconditionset?view=azureadps-2.0-preview&branch=pr-en-us-850) (azureadps-2.0-preview) |
[azureadps-2.0-preview/debug.log](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/debug.log) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202208231645185877-850/BuildReport?accessString=9dc8234f1f2c7de91dfc2dc2f898cec29c47e31cdcf77f9170869440919ac594).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[1f367d3](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/1f367d32148da8e0babe6bd16b7bf617c3af7ac4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmspermissiongrantconditionset?view=azureadps-2.0&branch=pr-en-us-850) (azureadps-2.0) |
[azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/limit-note/azureadps-2.0-preview/AzureAD/New-AzureADMSPermissionGrantConditionSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmspermissiongrantconditionset?view=azureadps-2.0-preview&branch=pr-en-us-850) (azureadps-2.0-preview) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/ed7d034d-a56c-a713-9d51-730d2ba643e8/202208231646101556-850/BuildReport?accessString=de02592dce764f50b32fd844edb71223b7d259ea11d7a87bd1866d17fbd0407b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
