### PR TITLE
Update Get-MsolUser.md

### PR DESCRIPTION
**Pull request by xavierihee**
Change from 'Phone Number' to 'PhoneNumber'
Change from 'Postal Code' to 'PostalCode'
Change from 'Preferred Data Location' to 'PreferredDataLocation' 
Change from 'Preferred Language' to 'PreferredLanguage'
Change from 'Proxy Addresses' to 'ProxyAddresses'

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[2183c6f](https://github.com/xavierihee/azure-docs-powershell-azuread/commits/2183c6ff9b902b4b6f66eebfa5b9154c0120e57d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-1.0/MSOnline/Get-MsolUser.md](https://github.com/xavierihee/azure-docs-powershell-azuread/blob/patch-1/azureadps-1.0/MSOnline/Get-MsolUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/msonline/get-msoluser?view=azureadps-1.0&branch=pr-en-us-710) (azureadps-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C8%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202109082024035175-710%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=rDlTdXGBOTBrdIzRbi2nle9CLKd4ZXeKKnhb0bqV9Q4%3D&st=2021-09-08T20%3A20%3A07Z&se=2021-10-09T20%3A25%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hello @xavierihee, thanks for your contribution. Please redo your PR with the base branch as master instead live as per the policy.

**Review by WingsBrokenAngel — APPROVED** [review]
It makes sense.

**Review by WingsBrokenAngel — CHANGES_REQUESTED** [review]
Please change the destination branch to master.

**Comment by msewaweru** [comment]
Closing this. Issue resolved in [PR 734](https://github.com/Azure/azure-docs-powershell-azuread/pull/734).

**Pull request closed without merging**
