### PR TITLE
Update Restore-AzureADDeletedApplication.md

### PR DESCRIPTION
**Pull request by PatAltimore**
Add note indicating service principal needs to be created after application restore.

### CODE REVIEW

**Comment by TaraMeyer** [comment]
@PatAltimore - looks like the build failed.  Can you try reformatting your note section to the correct format for note sections in MarkDown:  

[!NOTE]
This is where the text lives after a note after the note tag has been added.

**Comment by PatAltimore** [comment]
@TaraMeyer  Thanks.  I updated the note.

**Comment by PatAltimore** [comment]
@TaraMeyer Seems like it still failed.  I'll use standard markdown and try again.

**Comment by TaraMeyer** [comment]
@PatAltimore - yes I tried to fix on my end as well with the same results.  I had to escalate to Shanghai team, I'll let you know what they discover.

**Comment by PatAltimore** [comment]
@TaraMeyer Thanks!

**Comment by TaraMeyer** [comment]
@PatAltimore - the issue was a bug, all is resolved now.  I've merged to master and pushed live.

**Comment by PatAltimore** [comment]
@TaraMeyer - Cool.  Thanks!

**Pull request merged**
