### PR TITLE
json mapping deletion of "others"

### PR DESCRIPTION
**Pull request by v-cmans**
-5 from 2.0-preview
-36 from 2.0

### CODE REVIEW

**Comment by v-cmans** [comment]
decided to edit module pages

**Comment by RobdeJong** [comment]
Hi - can you explain why you are making this change?

**Comment by sankethka** [comment]
@RobdeJong This was done in error. we discussed and closed this PR. Tara will reach out to you on this issue shortly. 
CC @v-cmans

**Comment by RobdeJong** [comment]
OK, thanks, Sanketh. Got me worried for a moment 😊

**Pull request closed without merging**
