### PR TITLE
Made changes that came from public PRs but were done against the live…

### PR DESCRIPTION
**Pull request by msewaweru**
… branch

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[c393992](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/c3939927ffd84a4dba91fff52e3f573f6b9209fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryrole?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |
[azureadps-2.0/AzureAD/Get-AzureADUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/Get-AzureADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |
[azureadps-2.0/AzureAD/New-AzureADUserAppRoleAssignment.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/New-AzureADUserAppRoleAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduserapproleassignment?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C23%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107230641423158-662%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-21T10%3A43%3A01Z&ske=2021-07-28T10%3A48%3A01Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-23T06%3A37%3A45Z&se=2021-08-23T06%3A42%3A45Z&sr=b&sp=r&sig=Hxly81KPe909njk4bPeRLnWT5ySk9wYJaaU94B0HY3Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[9e2a0a1](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/9e2a0a18ddf53f53c49a2c635229ac9422b85f71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryrole?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |
[azureadps-2.0/AzureAD/Get-AzureADUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/Get-AzureADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |
[azureadps-2.0/AzureAD/New-AzureADUserAppRoleAssignment.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/New-AzureADUserAppRoleAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduserapproleassignment?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107280443545037-662%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A46%3A06Z&ske=2021-08-04T03%3A51%3A06Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T04%3A39%3A42Z&se=2021-08-28T04%3A44%3A42Z&sr=b&sp=r&sig=znNfxJRnP9C6iv4l55I%2BKCNagMYrBEV5wP3%2Bd40SCwo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[d3df905](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/d3df9057d07b7cb5c3a535dc09bd58919ef8f95b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryrole?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |
[azureadps-2.0/AzureAD/Get-AzureADUser.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/Get-AzureADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |
[azureadps-2.0/AzureAD/New-AzureADUserAppRoleAssignment.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/pr-consolidation/azureadps-2.0/AzureAD/New-AzureADUserAppRoleAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/azuread/new-azureaduserapproleassignment?view=azureadps-2.0&branch=pr-en-us-662) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C28%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107280446080279-662%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-28T03%3A33%3A54Z&ske=2021-08-04T03%3A38%3A54Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-28T04%3A42%3A03Z&se=2021-08-28T04%3A47%3A03Z&sr=b&sp=r&sig=Ip8nvomqO0d9snHhVSIRJGERkztUQ%2BPZkqjrdDXJcXQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
Hi @CelesteDG , this is a consolidation of the PRs that were submitted against the live branch. I redid them and closed the original PRs.

**Pull request merged**
