### PR TITLE
Fixes #625 - Update docfx.json to enable GitHub issues on the docs

### LINKED ISSUE #625: Submitting issues to pages in DOCS
From the [DOCs page,](https://docs.microsoft.com/en-us/powershell/module/azuread/open-azureadmsprivilegedroleassignmentrequest?view=azureadps-2.0-preview) one cannot open an issue directly here. 

Is that intentional?

### PR DESCRIPTION
**Pull request by msewaweru**

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[93dc300](https://github.com/Azure/azure-docs-powershell-azuread/commits/93dc30067863ddd6fe0e7b6de5a79ab072a0857f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docfx.json](https://github.com/Azure/azure-docs-powershell-azuread/blob/enable-github-issues/docfx.json) | :x:Error | | [Details](#user-content-2e59e625820a0649d8ada0a84573256e-c70a1fa6)

<a id="2e59e625820a0649d8ada0a84573256e-c70a1fa6"></a>
### [docfx.json](https://github.com/Azure/azure-docs-powershell-azuread/blob/enable-github-issues/docfx.json)
 - **Line 133, Column 6**: **[Error-json-syntax-error]** `````After parsing a value an unexpected character was encountered: ".`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202107090201521237-650%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A57%3A11Z&ske=2021-07-13T08%3A02%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T01%3A57%3A22Z&se=2021-08-09T02%3A02%3A22Z&sr=b&sp=r&sig=GM3BdhZCzmh7WJgM76mu8n1B5pwnBZsxbBi%2F0d4aMEQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by CelesteDG** [comment]
@msewaweru Flagging for you, Eunice.

**Comment by msewaweru** [comment]
> @msewaweru Flagging for you, Eunice.

Thanks @CelesteDG. There is some info I need to resolve this issue. I will update once I have it.

**Comment by msewaweru** [comment]
Recreating this PR from my fork.

**Pull request closed without merging**
