### PR TITLE
Updated the version history page with the current version of the Azur…

### PR DESCRIPTION
**Pull request by msewaweru**
…eAD and AzureAD Preview modules

### CODE REVIEW

**Comment by billmath** [comment]
Docs Build status updates of commit _[45adc46](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/45adc466d942f705124226cff1abbc7f4c104c1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/version-history-update/docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/ad-pshell-v2-version-history?view=azureadps-2.0&branch=pr-en-us-679) (azureadps-2.0) | [Details](#user-content-b67ff6e67d11afd037b20c11783631d0-92a677e0)

<a id="b67ff6e67d11afd037b20c11783631d0-92a677e0"></a>
### [docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/version-history-update/docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md)
 - **Line 44, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 '2.0.2.104 - General Availability release of the AzureAD module''. Each second level heading (H2) in an article must be unique.`````
 - **Line 68, Column 1**: **[Warning-[duplicate-h2s](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/duplicate-h2s?branch=master)]** `````Duplicate heading: 'H2 '2.0.2.104 - General Availability release of the AzureAD module''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C13%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202108131053442659-679%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=29B2Tvac6XJSqXtqE%2BcV7ArU5DfJgcweB3a9qTIxVKA%3D&st=2021-08-13T10%3A49%3A31Z&se=2021-09-13T10%3A54%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[e51411f](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/e51411fbc09380af18b063d51fe376c6e65bccac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/version-history-update/docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/ad-pshell-v2-version-history?view=azureadps-2.0&branch=pr-en-us-679) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C13%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202108131058201630-679%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ycVhlo9cvv3MwDmjuQ6M631skvPrkszrHAKOU3pKYkE%3D&st=2021-08-13T10%3A54%3A01Z&se=2021-09-13T10%3A59%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by billmath** [comment]
Docs Build status updates of commit _[231f392](https://github.com/msewaweru/azure-docs-powershell-azuread/commits/231f39225012012eeef3c56cb3f708981f1ec76d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md](https://github.com/msewaweru/azure-docs-powershell-azuread/blob/version-history-update/docs-conceptual/azureadps-2.0/ad-pshell-v2-version-history.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/azure/active-directory/ad-pshell-v2-version-history?view=azureadps-2.0&branch=pr-en-us-679) (azureadps-2.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C13%5Ced7d034d-a56c-a713-9d51-730d2ba643e8%5CPullRequest%5C202108131446019033-679%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Ggrvtvv6IZHPTBpRsdKbOijT97UXmwnNrxp3Z%2B1WNOM%3D&st=2021-08-13T14%3A41%3A50Z&se=2021-09-13T14%3A46%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ed7d034d-a56c-a713-9d51-730d2ba643e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by msewaweru** [comment]
@CelesteDG , please review this.

**Comment by msewaweru** [comment]
Hi @CelesteDG , I have updated the changes done in the most recent versions of the Azure AD and Azure AD Preview module. Though I have not gotten the descriptions for the new cmdlets in the Preview module, I suggest to update that when the information becomes available.

**Comment by CelesteDG** [comment]
Thank you for the updates, @msewaweru I'm good with this plan.

**Pull request merged**
